 const customers = [
  {
    firstName: 'Emannuel',
    lastName: 'Jean',
    email: 'w@j.com',
    birthDate: new Date(),
    address: 'here',
    city: 'santiago',
    state: 'San',
    zip: '500u9',
    country: 'haiti',
  },
  {
    firstName: 'Emannuel',
    lastName: 'Jean',
    email: 'w@j.com',
    birthDate: new Date(),
    address: 'here',
    city: 'santiago',
    state: 'San',
    zip: '500u9',
    country: 'haiti',
  },
  {
    firstName: 'Emannuel',
    lastName: 'Jean',
    email: 'w@j.com',
    birthDate: new Date(),
    address: 'here',
    city: 'santiago',
    state: 'San',
    zip: '500u9',
    country: 'haiti',
  },{
    firstName: 'g',
    lastName: 'h',
    email: 'w@j.com',
    birthDate: new Date(),
    address: 'here',
    city: 'santiago',
    state: 'San',
    zip: '500u9',
    country: 'haiti',
  },{
    firstName: 'man',
    lastName: 'paul',
    email: 'w@j.com',
    birthDate: new Date(),
    address: 'there',
    city: 'santiago',
    state: 'San',
    zip: '500u9',
    country: 'usa',
  },{
    firstName: 'Gearge',
    lastName: 'go',
    email: 'w@j.com',
    birthDate: new Date(),
    address: 'here',
    city: 'new york',
    state: 'gp',
    zip: '500u9',
    country: 'haiti',
  }
]
module.exports = customers